### ISSUE TITLE
Rename to common-php

### ISSUE THREAD

**Issue by nesl247** [LinioIT/common-php#12]
Hey everyone,

What do you think about renaming this package to common-php? We're starting to work in other languages a lot with AngularJS, Kotlin, GO, etc., and having a single package called `common` doesn't make sense as it's not common to all of our applications. Doing this would allow us to have a common package for each language if we wanted.

Let me know what you all think.

**Comment by bycosta** [comment]
I agree.

**Comment by damian-af** [comment]
I agree as well.

**Comment by nesl247** [comment]
I'd like to hear from @xurumelous and @klaussilveira before doing so. We should also change it on packagist I believe. I believe one of those two will have access.

**Comment by nesl247** [comment]
From what I see, packagist doesn't support renaming, so we're only going to rename the library.
